// Code generated by "stringer -type EventType event.go"; DO NOT EDIT

package event

import "fmt"

const _EventType_name = "ADD_SERVICEDEL_SERVICEADD_UPSTREAMDEL_UPSTREAMADD_ROUTERDEL_ROUTER"

var _EventType_index = [...]uint8{0, 11, 22, 34, 46, 56, 66}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
